### ISSUE TITLE
Or not and

### ISSUE THREAD

**Issue by agardnerIT** [dynatrace-oss/aws-health-events-integration#2]
Should this be an `OR` not an `AND`?

https://github.com/dynatrace-oss/aws-health-events-integration/blob/02a593e9e945e4bf049a5d2a404b929a61bd788f/awshealth2dynatrace/awsHealthEvent2DTEventFunction/index.js#L87

**Comment by MichaelStephan** [comment]
Hello, you are absolutely right; it should be an OR. I will provide a fix later today.

Cheers,
Michael

**Comment by MichaelStephan** [comment]
Fix was applied, thx for hinting towards it.
